image:
  file: .gitpod.Dockerfile
tasks:
  - name: Strapi
    init: >
      cd /workspace/foodadvisor/api &&
      yarn install &&
      yarn seed &&
      gp sync-done strapi
    command: yarn develop
  - name: Next.js
    init: |
      cd /workspace/foodadvisor/client &&
      gp sync-await strapi
      yarn install &&
    command: yarn dev
ports:
  - port: 1337
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public