# docker-compose.yml
services:
  api:
    image: ${DOCKERHUB_USERNAME}/foodadvisor-api:latest
    container_name: foodadvisor-api
    restart: unless-stopped
    env_file: api.env
    volumes:
      - ./uploads:/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - foodadvisor-network

  client:
    image: ${DOCKERHUB_USERNAME}/foodadvisor-client:latest
    container_name: foodadvisor-client
    restart: unless-stopped
    env_file: client.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - foodadvisor-network

networks:
  foodadvisor-network:
    driver: bridge

volumes:
  uploads: