version: '3.8'

services:
  api:
    image: ${DOCKERHUB_USERNAME}/foodadvisor-api:latest
    container_name: foodadvisor-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - STRAPI_ADMIN_CLIENT_URL=http://${PUBLIC_IP}:3000
      - STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=${PREVIEW_SECRET}
      - HOST=0.0.0.0
      - PORT=1337
    volumes:
      - ./uploads:/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - foodadvisor-network

  client:
    image: ${DOCKERHUB_USERNAME}/foodadvisor-client:latest
    container_name: foodadvisor-client
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://${PUBLIC_IP}:1337
      - PREVIEW_SECRET=${PREVIEW_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - foodadvisor-network

networks:
  foodadvisor-network:
    driver: bridge

volumes:
  uploads: