name: CD - Deploy to AWS

on:
  push:
    branches:
      - main 
      - develop
      - improvement-coding-and-documentation

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EC2 instance
        id: create-ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0230bd60aa48260c6 \
            --instance-type t2.medium \
            --key-name ${{ secrets.AWS_KP_NAME }} \
            --security-group-ids ${{ secrets.AWS_SG_ID }} \
            --user-data file://user-data.sh \
            --query 'Instances[0].InstanceId' \
            --output text)
          
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
          
          aws ec2 wait instance-running --instance-ids ${INSTANCE_ID}
          
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
            
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Deploy using Docker Compose
        env:
          INSTANCE_IP: ${{ steps.create-ec2.outputs.public_ip }}
          PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
        run: |
          # Save private key
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Create env file
          cat << EOF > .env
          DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
          JWT_SECRET=${JWT_SECRET}
          ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
          PUBLIC_IP=${INSTANCE_IP}
          PREVIEW_SECRET=$(openssl rand -hex 32)
          EOF
          
          # Copy files to EC2
          scp -i private_key.pem -o StrictHostKeyChecking=no .env docker-compose.yml ec2-user@${INSTANCE_IP}:~/
          
          # Deploy using Docker Compose
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${INSTANCE_IP} << 'EOF'
            # Source environment variables
            set -a
            source .env
            set +a
            
            # Pull and start containers
            docker-compose pull
            docker-compose up -d
            
            # Wait for containers to start
            echo "Waiting for containers to start..."
            sleep 30
            docker-compose ps
          EOF

      - name: Verify deployment
        env:
          INSTANCE_IP: ${{ steps.create-ec2.outputs.public_ip }}
        run: |
          echo "Verifying deployment..."
          curl --retry 5 --retry-delay 10 -f http://${INSTANCE_IP}:1337/admin || exit 1
          curl --retry 5 --retry-delay 10 -f http://${INSTANCE_IP}:3000 || exit 1
          echo "Deployment verified successfully!"

      - name: Cleanup on failure
        if: failure()
        env:
          INSTANCE_ID: ${{ steps.create-ec2.outputs.instance_id }}
        run: aws ec2 terminate-instances --instance-ids $INSTANCE_ID