name: Node.js CI

on:
  push:
  pull_request:
    branches: [ develop-feature06, develop, main ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu:latest', 'debian:latest', 'redhat/ubi8']
        node-version: [16.x , 18.x]
    
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install api dependencies
      working-directory: ./api
      run: |
        yarn global add jest
        yarn --force && yarn seed
        echo "JWT_SECRET=test-jwt-secret" >> .env
        echo "ADMIN_JWT_SECRET=test-admin-jwt-secret" >> .env
        npm install @babel/plugin-transform-runtime

    - name: Install client dependencies
      working-directory: ./client
      run: |
        yarn --force

    - name: build npm for each node version
      working-directory: ./api
      run: npm rebuild
    
    - name: Run api unit tests
      working-directory: ./api
      run: yarn test:unit
    
    - name: Run api integration tests
      working-directory: ./api
      run: yarn test:integration

    - name: Run client unit tests
      working-directory: ./client
      run: |
        yarn test:unit
    
    - name: Run client integration tests
      working-directory: ./client
      run: |
        yarn test:integration
