name: Node.js CI

on:
  push:
    branches: [ test-feature06, test-feature07, test-feature08 ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu:latest', 'debian:latest', 'redhat/ubi8']
        node-version: [16.x]
    
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Yarn
      run: npm install -g yarn

    - name: Install api dependencies
      working-directory: ./api
      run: |
        yarn add @babel/runtime
        yarn install
        yarn seed
        echo "JWT_SECRET=test-jwt-secret" >> .env
        echo "ADMIN_JWT_SECRET=test-admin-jwt-secret" >> .env

    - name: Install client dependencies
      working-directory: ./client
      run: yarn install
    
    - name: Run unit tests
      working-directory: ./client
      run: yarn test:unit
    
    - name: Run integration tests
      working-directory: ./client
      run: yarn test:integration
